### ISSUE TITLE
Node for Newbs Crash Course

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider-core#4]
@AntoineDao 

As per our meetup, how about writing up a crash course for Node for inexperienced users?

As time goes on we can customize and streamline so it focuses primarily on what AEC peeps need to know in order to get started quickly. And I can add comments from a guinea-pig point of view.

**Comment by theo-armour** [comment]
@AntoineDao 

Here is what I have so far:

### Objective

* See this https://www.ladybug.tools/spider-react/ - running locally

![image](https://user-images.githubusercontent.com/547626/55361038-d6f34d00-548a-11e9-9144-43040204bc14.png)


### Actions

* Go to https://nodejs.org/en/
* Click button on webpage to download Node xx.xx.xx LTS
* Install it - which also installs NPM vx.x.x
* Create folder 'spider-react' and change dir into it
* Open terminal window in 'spider-react'
* Verify node install with >node-v and >npm -v
* Install 'spider-react' using >npm install https://github.com/ladybug-tools/spider-react.git
    * Brew a cup of coffee/tea while it installs
* Install 'http-server' using >npm install http-server -g
* Cd in terminal window to: spider-react/node_modules/spider-react/public
* Start local host using >http-server

After that I navigated around and tried stuff but to no avail. 

To be continued...

**Comment by AntoineDao** [comment]
Mind creating a similar issue to this one in [spider-react](https://github.com/ladybug-tools/spider-react) and adding the comment above there? This repo is more dedicated to the data layer of the spider app.

**Comment by theo-armour** [comment]
@AntoineDao 

done
